CREATE TABLE Course (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    instructor VARCHAR(100) NOT NULL,
    categoryId BIGINT(20) NOT NULL,
    status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    inactivationDate DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_course_category FOREIGN KEY (categoryId) REFERENCES Category(id)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
ROW_FORMAT=DYNAMIC;